name: Build/release
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1.0.0
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: "Build"
        run: make release
      - name: "Publish"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/sha256sums.txt
            release/laminar-webform.darwin64.tar.gz
            release/laminar-webform.linux64.tar.gz
            release/laminar-webform.win64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
